runtime:
    platform: ${oc.env:PLATFORM,ascend_npu}

distributed:
    backend: auto
    timeout_minutes: 60

model:
    name: qwen_image
    pretrained_model_name_or_path: /data/wushuo1/models/Qwen-Image-2512
    max_sequence_length: 1024
    running_dtype: bf16

data:
    train:
        name: image_dataset
        num_workers: 4
        prompt_dropout_rate: 0.1
        target_area: 1048576
        shuffle: false
        data_path:
            - /data/wushuo1/data/LightX2V_train_data_examples/dataset_v1/train.jsonl

training:
    method: flow_matching

logging:
    rank_zero_only: true
