eval_parameters:
  evaluations_items: 
    eval_length_jump:
      thresh_length: 0.3
      length_win_size: 50
    eval_width_jump:
      thresh_width: 0.3
      width_win_size: 50
    eval_height_jump:
      thresh_height: 0.3
      height_win_size: 50
    eval_heading_jump:
      thresh_heading: 0.314
      heading_win_size: 25
    eval_type_jump: {}
    eval_short_track:
      thresh_short_track: 40
    eval_track_lost:
      skip_frame_time: 100 #ms
    eval_speed_jump:
      thresh_vector_speed_x: 5
      thresh_vector_speed_y: 5
      thresh_vector_speed_z: 5
      speed_win_size: 25
    eval_position_jump:
      thresh_position: 1.5
      skip_frame_time: 100 #ms
  eval_global_params:
    win_size: 50
    eval_object_types: 
    data_load: alt_data_loader
