model:
    name: qwen_image
    pretrained_model_name_or_path: /data/wushuo1/models/Qwen-Image-2512
    max_sequence_length: 1024
    running_dtype: bf16

distributed:
    backend: auto
    timeout_minutes: 120
    sequence_parallel:
        enabled: false
        size: 1
    fsdp2:
        enabled: true
        size: 8
        log_memory: true
        reshard_after_forward:
            root_reshard: false
            block_reshard: true
        mixed_precision:
            param_dtype: bf16
            reduce_dtype: fp32
            output_dtype: null
            cast_forward_inputs: false

data:
    val:
        name: image_dataset
        num_workers: 2
        shuffle: false
        data_path:
            - /data/wushuo1/data/LightX2V_train_data_examples/dataset_v1/val.jsonl

scheduler:
    num_train_timesteps: 1000
    timestep_distribution: logitnormal
    logitnormal_mean: 0.0
    logitnormal_std: 1.0
    min_sigma: 0.001
    max_sigma: 1.0
    time_shift_settings:
        do_time_shift: true
        shift_type: exponential
        time_shift_power: 1.0
        dynamic_shift: true
        shift_mu_strategy: linear
        patch_size: [2, 2]
        shift_x1: 256
        shift_x2: 8192
        shift_y1: 0.5
        shift_y2: 0.9

inference:
    method: image_infer
    negative_prompt: " "
    default_width: 1024
    default_height: 1024
    num_inference_steps: 50
    enable_cfg: true
    cfg_guidance_scale: 4.0
    seed: 42
    vae_cpu_offload: true
    vae_tiling: true
    output_dir: /data/wushuo1/exps_1002/outputs/final_infer
    lora_config:
        path: /data/wushuo1/exps_1002/outputs/checkpoints/checkpoint-000003000/pytorch_lora_weights.safetensors

logging:
    rank_zero_only: true
    infer_log_every_steps: 10
